channels:
  - conda-forge

# Almost all libraries should be added in requirements.txt
# Only libraries *not* available in PyPI should be here
dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.47.1
  - jupyter-archive==3.4.0
  - jupyter-resource-usage==1.1.0  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.15.0 
  - jupyterhub==5.2.1
  - jupyterlab==4.3.4
  - jupyterlab-git==0.50.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.1
  - notebook==7.3.2
  - pip==24.3.1  
  - python==3.11.*

  #adding math functionality
  - matplotlib==3.7.3
  - scipy==1.10.1
  - mpld3==0.5.10

  # Needed for linux desktop environment
  - websockify==0.11.0

  - qgis==3.40.2

  # Maybe needed for qgis? https://github.com/conda-forge/qgis-feedstock/issues/263
  - pyopencl==2024.3

  - pip:
    # For desktop environment
    - jupyter-desktop-server==0.1.3
    - otter-grader==6.0.4
    # for notebook exporting
    - nb2pdf==0.6.2
    - nbpdfexport==0.2.1
    - nbconvert[webpdf]==7.16.5
    - git-credential-helpers==0.2
