#!/bin/bash
set -eou pipefail

# HORRIBLE HACK to get qgis working. conda-forge brings in libgsl 2.7, but this seems
# to require libgsl 2.5? And I can't force conda to install that. This might break something
# deep somewhere. See https://github.com/conda-forge/qgis-feedstock/issues/263
# for upstream discussion
#ln -s /srv/conda/envs/notebook/lib/libgsl.so.27 /srv/conda/envs/notebook/lib/libgsl.so.25

# webpdf
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium
      for notebook in image-tests/*.ipynb; do
          jupyter nbconvert --to webpdf "$notebook"
          if [ ! -f "${notebook%.ipynb}.pdf" ]; then
              echo "Error: PDF conversion failed for $notebook"
              exit 1
          fi
      done
