#!/bin/bash
set -euo pipefail

mkdir -p $HOME/Desktop
cp $REPO_DIR/*.desktop $HOME/Desktop/

# See https://jira-secure.berkeley.edu/browse/DH-305
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}

exec "$@"
